export const BRAND_LIST_REQUEST = "BRAND_LIST_REQUEST";
export const BRAND_LIST_SUCCESS = "BRAND_LIST_SUCCESS";
export const BRAND_LIST_FAIL = "BRAND_LIST_FAIL";
export const HOME_BRAND_LIST_REQUEST = "HOME_BRAND_LIST_REQUEST";
export const HOME_BRAND_LIST_SUCCESS = "HOME_BRAND_LIST_SUCCESS";
export const HOME_BRAND_LIST_FAIL = "HOME_BRAND_LIST_FAIL";