export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_WAIT_ITEM = "CART_WAIT_ITEM";
export const CART_ITEM_SUCCESS = "CART_ITEM_SUCCESS";
export const CART_ITEM_FAIL = "CART_ITEM_FAIL";
export const CART_CLEAR_ITEMS = "CART_RESET";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_UPDATE_SHIPPING_ADDRESS = "CART_UPDATE_SHIPPING_ADDRESS";
export const CART_UPDATE_BILLING_ADDRESS = "CART_UPDATE_BILLING_ADDRESS";

export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_SAVE_BILLING_ADDRESS = "CART_SAVE_BILLING_ADDRESS";
export const ADDRESS_UPDATE_REQUEST = "ADDRESS_UPDATE_REQUEST";
export const ADDRESS_UPDATE_SUCCESS = "ADDRESS_UPDATE_SUCCESS";
export const ADDRESS_UPDATE_FAIL = "ADDRESS_UPDATE_FAIL";

export const BILLING_ADDRESS_UPDATE_REQUEST = "BILLING_ADDRESS_UPDATE_REQUEST";
export const BILLING_ADDRESS_UPDATE_SUCCESS = "BILLING_ADDRESS_UPDATE_SUCCESS";
export const BILLING_ADDRESS_UPDATE_FAIL = "BILLING_ADDRESS_UPDATE_FAIL";

export const CHECK_COUPON_REQUEST = "CHECK_COUPON_REQUEST";
export const CHECK_COUPON_SUCCESS = "CHECK_COUPON_SUCCESS";
export const CHECK_COUPON_FAIL = "CHECK_COUPON_FAIL";
