export const EVENT_CAROUSEL_REQUEST = "EVENT_CAROUSEL_REQUEST";
export const EVENT_CAROUSEL_SUCCESS = "EVENT_CAROUSEL_SUCCESS";
export const EVENT_CAROUSEL_FAIL = "EVENT_CAROUSEL_FAIL";

export const SINGLE_EVENT_REQUEST = "SINGLE_EVENT_REQUEST";
export const SINGLE_EVENT_SUCCESS = "SINGLE_EVENT_SUCCESS";
export const SINGLE_EVENT_FAIL = "SINGLE_EVENT_FAIL";
