export const HOME_CATEGORY_LIST_REQUEST = "HOME_CATEGORY_LIST_REQUEST";
export const HOME_CATEGORY_LIST_SUCCESS = "HOME_CATEGORY_LIST_SUCCESS";
export const HOME_CATEGORY_LIST_FAIL = "HOME_CATEGORY_LIST_FAIL";

export const HOT_DEALS_LIST_REQUEST = "HOT_DEALS_LIST_REQUEST";
export const HOT_DEALS_LIST_SUCCESS = "HOT_DEALS_LIST_SUCCESS";
export const HOT_DEALS_LIST_FAIL = "HOT_DEALS_LIST_FAIL";
