export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const SINGLE_PRODUCT_LIST_REQUEST = "SINGLE_PRODUCT_LIST_REQUEST";
export const SINGLE_PRODUCT_LIST_SUCCESS = "SINGLE_PRODUCT_LIST_SUCCESS";
export const SINGLE_PRODUCT_LIST_FAIL = "SINGLE_PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_TOP_REQUEST = "PRODUCT_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_FAIL = "PRODUCT_TOP_FAIL";

export const WISH_LIST_REQUEST = "WISH_LIST_REQUEST";
export const WISH_LIST_SUCCESS = "WISH_LIST_SUCCESS";
export const WISH_LIST_FAIL = "WISH_LIST_FAIL";
export const WISH_LIST_REMOVE = "WISH_LIST_REMOVE";

export const WISH_LIST_GET_REQUEST = "WISH_LIST_GET_REQUEST";
export const WISH_LIST_GET_SUCCESS = "WISH_LIST_GET_SUCCESS";
export const WISH_LIST_GET_FAIL = "WISH_LIST_GET_FAIL";
export const WISH_LIST_GET_REMOVE = "WISH_LIST_GET_REMOVE";

export const WISH_LIST_REMOVE_REQUEST = "WISH_LIST_REMOVE_REQUEST";
export const WISH_LIST_REMOVE_SUCCESS = "WISH_LIST_REMOVE_SUCCESS";
export const WISH_LIST_REMOVE_FAIL = "WISH_LIST_REMOVE_FAIL";
export const WISH_LIST_REMOVE_REMOVE = "WISH_LIST_REMOVE_REMOVE";

export const BRAND_PRODUCT_DETAILS_REQUEST = "BRAND_PRODUCT_DETAILS_REQUEST";

export const PRODUCT_SALE_REQUEST = "PRODUCT_SALE_REQUEST";
export const PRODUCT_SALE_SUCCESS = "PRODUCT_SALE_SUCCESS";
export const PRODUCT_SALE_FAIL = "PRODUCT_SALE_FAIL";
export const LIST_PRODUCT_REQUEST = "LIST_PRODUCT_REQUEST";
export const LIST_PRODUCT_SUCCESS = "LIST_PRODUCT_SUCCESS";
export const LIST_PRODUCT_FAIL = "LIST_PRODUCT_FAIL";
