export const STATE_LIST_REQUEST = "STATE_LIST_REQUEST";
export const STATE_LIST_SUCCESS = "STATE_LIST_SUCCESS";
export const STATE_LIST_FAIL = "STATE_LIST_FAIL";
export const HOME_STATE_LIST_REQUEST = "HOME_STATE_LIST_REQUEST";
export const HOME_STATE_LIST_SUCCESS = "HOME_STATE_LIST_SUCCESS";
export const HOME_STATE_LIST_FAIL = "HOME_STATE_LIST_FAIL";
