export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const TOP_NAV_REQUEST = "TOP_NAV_REQUEST";
export const TOP_NAV_REQUEST_SUCCESS = "TOP_NAV_REQUEST_SUCCESS";
export const TOP_NAV_REQUEST_FAIL = "TOP_NAV_REQUEST_FAIL";

export const GET_CATEGARY_REQUEST = "GET_CATEGARY_REQUEST";
export const GET_CATEGARY_REQUEST_SUCCESS = "GET_CATEGARY_REQUEST_SUCCESS";
export const GET_CATEGARY_REQUEST_FAIL = "GET_CATEGARY_REQUEST_FAIL";

export const GET_BAGSIZE_REQUEST = "GET_BAGSIZE_REQUEST";
export const GET_BAGSIZE_REQUEST_SUCCESS = "GET_BAGSIZE_REQUEST_SUCCESS";
export const GET_BAGSIZE_REQUEST_FAIL = "GET_BAGSIZE_REQUEST_FAIL";

export const GET_MATERIAL_REQUEST = "GET_MATERIAL_REQUEST";
export const GET_MATERIAL_REQUEST_SUCCESS = "GET_MATERIAL_REQUEST_SUCCESS";
export const GET_MATERIAL_REQUEST_FAIL = "GET_MATERIAL_REQUEST_FAIL";

export const GET_COLOR_REQUEST = "GET_COLOR_REQUEST";
export const GET_COLOR_REQUEST_SUCCESS = "GET_COLOR_REQUEST_SUCCESS";
export const GET_COLOR_REQUEST_FAIL = "GET_COLOR_REQUEST_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const BILLING_ADDRESS_MODIFCATION_REQUEST =
  "BILLING_ADDRESS_MODIFCATION_REQUEST";
export const BILLING_ADDRESS_MODIFCATION_SUCCESS =
  "BILLING_ADDRESS_MODIFCATION_SUCCESS";
export const BILLING_ADDRESS_MODIFCATION_FAIL =
  "BILLING_ADDRESS_MODIFCATION_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";


export const SINGLE_USER_DETAIL_REQUEST = "SINGLE_USER_DETAIL_REQUEST";
export const SINGLE_USER_DETAIL_SUCCESS = "SINGLE_USER_DETAIL_SUCCESS";
export const SINGLE_USER_DETAIL_FAIL = "SINGLE_USER_DETAIL_FAIL";
export const SINGLE_USER_DETAIL_RESET = "SINGLE_USER_DETAIL_RESET";

export const USERS_DETAIL_REQUEST = "USERS_DETAIL_REQUEST";
export const USERS_DETAIL_SUCCESS = "USERS_DETAIL_SUCCESS";
export const USERS_DETAIL_FAIL = "USERS_DETAIL_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";

export const ADD_WHISHLIST_REQUEST = "ADD_WHISHLIST_REQUEST";
export const WHISHLIST_REQUEST_SUCCESS = "WHISHLIST_REQUEST_SUCCESS";
export const WHISHLIST_REQUEST_FAIL = "WHISHLIST_REQUEST_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const VERIFY_USER_REQUEST = "VERIFY_USER_REQUEST";
export const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS";
export const VERIFY_USER_FAIL = "VERIFY_USER_FAIL";

export const GET_NEWDROP_REQUEST = "GET_NEWDROP_REQUEST";
export const GET_NEWDROP_REQUEST_SUCCESS = "GET_NEWDROP_REQUEST_SUCCESS";
export const GET_NEWDROP_REQUEST_FAIL = "GET_NEWDROP_REQUEST_FAIL";

export const ORDER_CREATE_REQUEST="ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL="ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_PAY_REQUEST="ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS="ORDER_PAY_SUCCESS";
export const ORDER_PAY_RESET ="ORDER_PAY_RESET";
export const ORDER_PAY_FAIL="ORDER_PAY_FAIL";

export const GET_MYWOLFPACK_ORDER_REQUEST="GET_MYWOLFPACK_ORDER_REQUEST";
export const GET_MYWOLFPACK_ORDER_SUCCESS="GET_MYWOLFPACK_ORDER_SUCCESS";
export const GET_MYWOLFPACK_ORDER_FAIL="GET_MYWOLFPACK_ORDER_FAIL";
export const GET_MYWOLFPACK_ORDER_RESET="GET_MYWOLFPACK_ORDER_RESET";

export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAIL = "USER_FORGOT_PASSWORD_FAIL";
export const USER_FORGOT_PASSWORD_RESET = "USER_FORGOT_PASSWORD_RESET";

export const UPDATE_FORGET_PASSWORD_REQUEST = "UPDATE_FORGET_PASSWORD_REQUEST";
export const UPDATE_FORGET_PASSWORD_SUCCESS = "UPDATE_FORGET_PASSWORD_SUCCESS";
export const UPDATE_FORGET_PASSWORD_FAIL = "UPDATE_FORGET_PASSWORD_FAIL";
export const UPDATE_FORGET_PASSWORD_RESET = "UPDATE_FORGET_PASSWORD_RESET";




