export const WISHLIST_ADD_ITEM = "WISHLIST_ADD_ITEM";
export const WISHLIST_WAIT_ITEM = "WISHLIST_WAIT_ITEM";
export const WISHLIST_ITEM_SUCCESS = "WISHLIST_ITEM_SUCCESS";
export const WISHLIST_ITEM_FAIL = "WISHLIST_ITEM_FAIL";
export const WISHLIST_CLEAR_ITEMS = "WISHLIST_RESET";
export const WISHLIST_REMOVE_ITEM = "WISHLIST_REMOVE_ITEM";
export const WISHLIST_SAVE_SHIPPING_ADDRESS = "WISHLIST_SAVE_SHIPPING_ADDRESS";
export const WISHLIST_UPDATE_SHIPPING_ADDRESS = "WISHLIST_UPDATE_SHIPPING_ADDRESS";
export const WISHLIST_UPDATE_BILLING_ADDRESS = "WISHLIST_UPDATE_BILLING_ADDRESS";

export const WISHLIST_SAVE_PAYMENT_METHOD = "WISHLIST_SAVE_PAYMENT_METHOD";
export const WISHLIST_SAVE_BILLING_ADDRESS = "WISHLIST_SAVE_BILLING_ADDRESS";
export const ADDRESS_UPDATE_REQUEST = "ADDRESS_UPDATE_REQUEST";
export const ADDRESS_UPDATE_SUCCESS = "ADDRESS_UPDATE_SUCCESS";
export const ADDRESS_UPDATE_FAIL = "ADDRESS_UPDATE_FAIL";

export const BILLING_ADDRESS_UPDATE_REQUEST = "BILLING_ADDRESS_UPDATE_REQUEST";
export const BILLING_ADDRESS_UPDATE_SUCCESS = "BILLING_ADDRESS_UPDATE_SUCCESS";
export const BILLING_ADDRESS_UPDATE_FAIL = "BILLING_ADDRESS_UPDATE_FAIL";

export const CHECK_COUPON_REQUEST = "CHECK_COUPON_REQUEST";
export const CHECK_COUPON_SUCCESS = "CHECK_COUPON_SUCCESS";
export const CHECK_COUPON_FAIL = "CHECK_COUPON_FAIL";
